# Generated by Django 4.2.1 on 2024-08-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
