# Generated by Django 4.2.1 on 2024-08-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
