# Generated by Django 4.2.1 on 2024-08-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_sellerregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerRegistration',
        ),
    ]
