# Generated by Django 4.2.1 on 2024-08-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_sellerregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerregistration',
            name='user',
        ),
    ]
