# Generated by Django 4.2.1 on 2024-08-24 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_sellerregistration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCreation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
