# Generated by Django 4.2.1 on 2024-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_passwordcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('cancelled_cheque', models.ImageField(upload_to='cheques/')),
                ('bank_signature', models.ImageField(upload_to='signatures/')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=50)),
                ('business_description', models.TextField()),
            ],
        ),
    ]
