# Generated by Django 4.2.1 on 2024-08-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_sellerregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCreation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=255)),
                ('pickup_pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
