# Generated by Django 4.2.1 on 2024-08-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_bankdetails_businessdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='BusinessDetails',
        ),
        migrations.DeleteModel(
            name='PasswordCreation',
        ),
        migrations.DeleteModel(
            name='SellerRegistration',
        ),
    ]
