# Generated by Django 4.2.1 on 2024-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=10)),
                ('pickup_pincode', models.CharField(max_length=6)),
                ('pickup_address', models.TextField()),
                ('business_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('bank_account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('cancelled_cheque', models.ImageField(upload_to='documents/')),
                ('store_details', models.TextField()),
                ('sign_image', models.ImageField(upload_to='signatures/')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
