# Generated by Django 4.2.1 on 2024-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('gst', models.CharField(max_length=15)),
                ('business_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15)),
                ('business_pan_card', models.CharField(max_length=20)),
                ('cheque_passbook_photo', models.ImageField(upload_to='cheques_passbooks/')),
                ('sign', models.ImageField(upload_to='signatures/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
