# Generated by Django 4.2.1 on 2024-08-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_sellerprofile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='gst',
        ),
    ]
