# Generated by Django 4.2.1 on 2024-08-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_sellerprofile_business_pan_card_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
