# Generated by Django 4.2.1 on 2024-08-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
