# Generated by Django 4.2.1 on 2024-08-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
