# Generated by Django 4.2.1 on 2024-08-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_seller_otp_seller_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='password',
            new_name='set_password',
        ),
    ]
