# Generated by Django 4.2.1 on 2024-08-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_rename_password_seller_set_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='set_password',
            new_name='password',
        ),
    ]
