# Generated by Django 4.2.1 on 2024-08-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_rename_set_password_seller_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='otp_generated_at',
        ),
    ]
