# Generated by Django 4.2.1 on 2024-08-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_remove_seller_otp_remove_seller_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], default='seller', max_length=10),
        ),
    ]
