# Generated by Django 4.2.1 on 2024-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_seller_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller_admin', 'Seller Admin'), ('basic_seller', 'Basic Seller')], default='basic_seller', max_length=20),
        ),
    ]
