# Generated by Django 4.2.1 on 2024-08-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_seller_last_login_alter_seller_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='account_holder_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='account_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='ifsc_code',
            field=models.CharField(default='unknown', max_length=11),
            preserve_default=False,
        ),
    ]
