# Generated by Django 4.2.1 on 2024-08-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_seller_account_holder_name_seller_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='business_pan_card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
