# Generated by Django 4.2.1 on 2024-08-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
