# Generated by Django 4.2.1 on 2024-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=15)),
                ('business_pan_card', models.CharField(max_length=20)),
                ('cheque_passbook_photo', models.ImageField(upload_to='documents/')),
                ('sign', models.ImageField(upload_to='signatures/')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
            ],
        ),
    ]
