# Generated by Django 4.2.1 on 2024-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_pan_card',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='cheque_passbook_photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='sign',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
