# Generated by Django 4.2.1 on 2024-09-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_seller_delete_sellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
    ]
