# Generated by Django 4.2.1 on 2024-09-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_sellerprofile_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='cheque_passbook_photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='sign',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
