# Generated by Django 4.2.1 on 2024-09-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_sellerprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
