# Generated by Django 4.2.1 on 2024-09-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_sellerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
