# Generated by Django 4.2.1 on 2024-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
