# Generated by Django 4.2.1 on 2024-09-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_sellerprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
