# Generated by Django 4.2.1 on 2024-09-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_sellerprofile_is_pending_sellerprofile_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
