# Generated by Django 4.2.1 on 2024-09-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_seatingoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SeatingOption',
        ),
    ]
