# Generated by Django 4.2.1 on 2024-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_product_seating_delete_seatingoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
