# Generated by Django 4.2.1 on 2024-09-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_alter_product_seating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seating',
        ),
    ]
