# Generated by Django 4.2.1 on 2024-09-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=50)),
                ('seat_material', models.CharField(blank=True, max_length=100, null=True)),
                ('seat_color', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='store.product')),
            ],
        ),
    ]
