# Generated by Django 4.2.1 on 2024-09-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_price',
        ),
    ]
