# Generated by Django 4.2.1 on 2024-09-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_remove_seat_seat_color_remove_seat_seat_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seat_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('backrest_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mattress_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
