# Generated by Django 4.2.1 on 2024-09-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_delete_dimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seat_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('backrest_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mattress_size', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension', to='store.product')),
            ],
        ),
    ]
