# Generated by Django 4.2.1 on 2024-09-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_remove_dimension_backrest_height_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dimension',
        ),
    ]
