# Generated by Django 4.2.1 on 2024-09-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_dimension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dimension',
        ),
    ]
