# Generated by Django 4.2.1 on 2024-09-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_customcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCategory',
        ),
    ]
