# Generated by Django 4.2.1 on 2024-09-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_customrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_requests/'),
        ),
    ]
