# Generated by Django 4.2.1 on 2024-09-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0098_customrequest_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomRequest',
        ),
    ]
