# Generated by Django 4.2.1 on 2024-09-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0103_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
