# Generated by Django 4.2.1 on 2024-09-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0108_orders_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
