# Generated by Django 4.2.1 on 2024-10-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0112_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
