# Generated by Django 4.2.1 on 2024-10-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0115_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
