# Generated by Django 4.2.1 on 2024-10-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0117_orders_razorpay_order_id_orders_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
