# Generated by Django 4.2.1 on 2024-10-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0118_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.sellerprofile'),
            preserve_default=False,
        ),
    ]
