# Generated by Django 4.2.1 on 2024-10-19 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0119_orders_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sellerprofile'),
        ),
    ]
