# Generated by Django 4.2.1 on 2024-10-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0123_rename_quantity_orders_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='cart_quantity',
            new_name='quantity',
        ),
    ]
