# Generated by Django 4.2.1 on 2024-10-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0125_rename_cart_quantity_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tracking_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
