# Generated by Django 4.2.1 on 2024-10-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0127_orders_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
